
version: 2.1
jobs:
  build:
    docker:
    - image: cimg/base:stable
    - image: cimg/postgres:14.4
      environment:
        PGDATA: /dev/shm/pgdata/data
        POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run: echo "hello wowwaaa"
