
version: 2.1
jobs:
  build:
    docker:
    - image: cimg/ruby:3.1.2-browsers
    - image: cimg/postgres:13.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: echo "hello wowwaaaaaa"
      - run: sleep 3
      - run: psql -U postgres -h localhost -q -d circle_test -c "SELECT * FROM students;"
#      - run: psql -U postgres -h localhost -q -d circle_test -f dump.sql
