
version: 2.1
jobs:
  build:
    docker:
    - image: cimg/base:stable
    - image: cimg/postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run: echo "hello wowwaaa"
      - run: psql -U postgres -h localhost -q -d circle_test -c "SELECT * FROM students;"
#      - run: psql -U postgres -h localhost -q -d circle_test -f dump.sql
